disabled_rules:
- line_length
- colon
- trailing_whitespace
- force_cast
- variable_name
- type_name
- control_statement
- force_try
- implicit_getter

excluded:
- Carthage
- Pods

included:
- train your memory
- train your memory/models
- train your memory/ui/main
- train your memory/ui/statistics
- train your memory/ui/win
- train your memory/game
- train your memory/game/cells
- train your memory/loading
- train your memory/menu
